language: java
jdk: oraclejdk8
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - juraj.zachar@gmail.com

script: mvn clean verify package

#TODO how to deploy to public repo with travis + ssh key + no password input?
